context:
  version: "3.5.1"

package:
  name: "delphes"
  version: ${{ version }}

source:
  url: https://github.com/delphes/delphes/archive/refs/tags/${{ version }}.tar.gz
  sha256: b60d26d2ee2c84b58fbf2cf397fabd0ef3e89d3a0546d843c4ada82cc802d787
  patches:
    # std::prev_permutation needs <algorithm>, not transitively included on osx
    - add-missing-algorithm-include.patch
    # Adds DelphesPythia8Filtered (DelphesPythia8 + ResonanceDecayFilterHook)
    # c.f. https://github.com/qibin2020/delphes/commit/2104fd9
    - Add-ResonanceDecayFilterHook.patch

build:
  number: 3
  skip:
    - win
  script:
    # Make the examples location independent by removing the 'external/' prefix
    # in includes to instead use the installed versions
    - grep -r -l "external/" examples/ | xargs sed -i 's|external/||g'
    - CXXFLAGS="${CXXFLAGS}" cmake ${CMAKE_ARGS} -DPYTHIA8_DATA=$(pythia8-config --datadir) -S . -B build
    - cmake build -LH
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
    - grep
    - sed
  host:
    - root_base
    - root_cxx_standard
    - pythia8
  run_exports:
    - ${{ pin_subpackage("delphes", upper_bound="x.x.x") }}

tests:
  - package_contents:
      bin:
        - DelphesHepMC2
        - DelphesHepMC3
        - DelphesLHEF
        - DelphesPythia8
        - DelphesPythia8Filtered
        - DelphesROOT
        - DelphesSTDHEP

  - script:
      - curl -sLO https://github.com/hep-packaging-coordination/conda-forge-test-files/raw/refs/heads/main/delphes/z_ee.hep.gz
      - gunzip z_ee.hep.gz
      - DelphesSTDHEP "${PREFIX}"/cards/delphes_card_CMS.tcl delphes_output.root z_ee.hep

      # avoid lots of output to stdout
      - root -l -b -q "${PREFIX}"/examples/Example1.C'("delphes_output.root")' &> /dev/null
      - root -l -b -q "${PREFIX}"/examples/Example2.C'("delphes_output.root")'
      - root -l -b -q "${PREFIX}"/examples/Example3.C'("delphes_output.root")'
      - root -l -b -q "${PREFIX}"/examples/Example4.C'("delphes_output.root", "plots.root")'
      - root -l -b -q "${PREFIX}"/examples/Example5.C'("delphes_output.root")' &> /dev/null
      # FIXME: Example6.C is failing in CI but not locally
      # - root -l -b -q $PREFIX/examples/Example6.C'("delphes_output.root")'

    requirements:
      run:
        - root_base
        - pythia8
        - gzip
        - curl
        - grep
        - sed

about:
  summary: 'A framework for fast simulation of a generic collider experiment'
  description: |
    Delphes is a C++ framework, performing a fast multipurpose detector
    response simulation. The simulation includes a tracking system, embedded
    into a magnetic field, calorimeters and a muon system. The framework is
    interfaced to standard file formats (e.g. Les Houches Event File or HepMC)
    and outputs observables such as isolated leptons, missing transverse energy
    and collection of jets which can be used for dedicated analyses.
    The simulation of the detector response takes into account the effect of
    magnetic field, the granularity of the calorimeters and sub-detector resolutions.
    Visualisation of the final state particles is also built-in using the
    corresponding ROOT library.
  license: GPL-3.0-or-later
  license_file: COPYING
  homepage: https://github.com/delphes/delphes
  documentation: https://cp3.irmp.ucl.ac.be/projects/delphes
  repository: https://github.com/delphes/delphes

extra:
  recipe-maintainers:
    - pavel-demin
    - matthewfeickert
    - kratsg
